export enum FETCH_LATEST {
  LOADING = "FETCH_LATEST_LOADING",
  SUCCESS = "FETCH_LATEST_SUCCESS",
  FAILURE = "FETCH_LATEST_FAILURE",
}

export enum FETCH_FREQUENT {
  LOADING = "FETCH_FREQUENT_LOADING",
  SUCCESS = "FETCH_FREQUENT_SUCCESS",
  FAILURE = "FETCH_FREQUENT_FAILURE",
}
